---
title: "MARC Session Planning Form"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

| Leader Name: Jacob Green | Course: Planning form temp     |
|--------------------------|--------------------------------|
| Date created:10/7/2020   | Date implemented:10/9/2020     |
| Week in course:5         | Resources:Need to find         |

## Step 1: Meet with coordinators and discuss the following:
Useful resource; **"Identifying the Difficulties with Difficult Ideas"**

1. List the most important concepts and skill introduced in this topic
    a. Concepts
      * Read the Question
      * Writing in confidence
      * Opening statements are crucial!
      * Integrate information from the university
      * Topic vs theme
      * Do not use your first draft!

    b. Skills
      * Answering the tough questions
      * Finding good editors
      * Writing to answer the question
      * Getting your heart on the page
      * Tranforming casual language into academic language
      * Connecting your resume/CV to your personal statement

2. Which concepts and skills can be the most challenging for researchers this week? Why?

## Step 2: Plan your session based on who is attending in the lecture and meeting with the instructor
When planning your sessions remember to stay flexible with the actual implementation of your session plan. Trainees may come prepared with their own questions and agenda. Stay open to their requests. Useful handouts; **Bloom's Taxonomy, Learning Outcome ABC's, S.M.A.R.T, Strategy Du Jour.**

1. **Session Learning Objectives**
Describe what you would like to see your trainees be able to do by the end of your sessions? Use the list of concepts and skills you identified in Step #1.

I would like trainees to be familiar with a structured process to approach writing personal statements.

I would like trainees engage in a small writing groups. Here they will articulate the opening paragraph of a personal statement and have a dialouge with one other student about the content and writing style of that paragraph. 

2. **Check-in**
Allow for a 10-20 minute period where trainees are able to communicate with coordinators and each other about the weeks goals, trials, and tribulations.

3. **Warm-up**
Describe a 10-15 minute opportunity that will help trainees to organize, prioritize, define, identify, label, list, record, or review, ideas.

What are your aspirations? 
Take (x) minutes to write a short response to this question. Emphasis on content, not on style, talk in your own voice.

4. **Most of the session time**
Describe how you will utilize the meeting activity (50-60 minutes) to help trainees achieve the learning objectives you have developed.

This session will be split into two parts

Part 1: Discussion about the three stages of personal statements
Part 2: workshop on personal statement openings

In part 1 I will go over the three statges of personal statements (see powerpoint in resources)

In part 2 I will pair trainees with each other based on their goals. If they would like to workshop with another trainees ill create a breakout room for them. If not it is time to shut up and write for a bit. 

5. **Wrap-up**
Describe a 10-15 minute closing opportunity that will help trainees summarize their work in today's session. 

What was most useful for you?

What do you need me to consider?

What do you need from us?

## Step 3: Reflect on this week's session
Once you have hosted the session and completed the reflection share your completed session plan with your coordinators and review all of the activites from that week.

**1. What worked in the session? What was successful?**

**2. What did trainees learn? How do you know?**

**3. What would you change about your session today?**

**4. What specific content areas and study strategies did you recommend that trainees pursue before next week's sessions?**

**5. What are you considering as good use of next week's session?**

